name: CI Pipeline Hanoi Towers

on:
  pull_request:
    branches:
      - master
      - develop
      - workflow-test
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop-test

jobs:
  build-and-test-backend:
    outputs:
      lint: ${{ steps.lint.outputs.result }}
      build: ${{ steps.build.outputs.result }}
      test: ${{ steps.test.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        if: steps.changes.outputs.backend == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        if: steps.changes.outputs.backend == 'true'
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        continue-on-error: true

      - name: Linting Backend
        id: lint
        if: steps.changes.outputs.backend == 'true'
        uses: github/super-linter@v4
        env:
          VALIDATE_KOTLIN: true
          FILTER_REGEX_INCLUDE: '.*hanoi-backend/src/main/kotlin/hanoi.towers/application/.*'
          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Capture Lint Result
        if: steps.changes.outputs.backend == 'true'
        run: echo "result=${{ steps.lint.outcome }}" >> "$GITHUB_OUTPUT"

      - name: Build Project
        id: build
        if: steps.changes.outputs.backend == 'true'
        run: ./gradlew build
        continue-on-error: true
      - name: Capture Build Result
        if: steps.changes.outputs.backend == 'true'
        run: echo "result=${{ steps.build.outcome }}" >> "$GITHUB_OUTPUT"

      - name: Run Unit Tests
        id: test
        if: steps.changes.outputs.backend == 'true'
        run: ./gradlew :hanoi-backend:test jacocoTestReport
        continue-on-error: true
      - name: Capture Test Result
        if: steps.changes.outputs.backend == 'true'
        run: echo "result=${{ steps.test.outcome }}" >> "$GITHUB_OUTPUT"

      - name: Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 10
          min-coverage-changed-files: 0

  build-and-test-frontend:
    outputs:
      lint: ${{ steps.lint.outputs.result }}
      build: ${{ steps.build.outputs.result }}
      test: ${{ steps.test.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - if: steps.changes.outputs.frontend == 'true'
        run: echo "Changes detected"

      - name: Set up JDK
        if: steps.changes.outputs.frontend == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        if: steps.changes.outputs.frontend == 'true'
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        continue-on-error: true

      - name: Linting Frontend
        id: lint
        if: steps.changes.outputs.frontend == 'true'
        uses: github/super-linter@v4
        env:
          VALIDATE_KOTLIN: true
          FILTER_REGEX_INCLUDE: '.*hanoi-frontend/src/jsMain/kotlin/hanoi.towers/.*'
          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Capture Lint Result
        if: steps.changes.outputs.frontend == 'true'
        run: echo "result=${{ steps.lint.outcome }}" >> "$GITHUB_OUTPUT"

      - name: Build Project
        id: build
        if: steps.changes.outputs.frontend == 'true'
        run: ./gradlew hanoi-frontend:build
        continue-on-error: true
      - name: Capture Build Result
        if: steps.changes.outputs.frontend == 'true'
        run: echo "result=${{ steps.build.outcome }}" >> "$GITHUB_OUTPUT"

      - name: Run GUI Tests
        id: test
        if: steps.changes.outputs.frontend == 'true'
        run: ./gradlew :hanoi-frontend:jsTest
        continue-on-error: true
      - name: Capture Test Result
        if: steps.changes.outputs.frontend == 'true'
        run: echo "result=${{ steps.test.outcome }}" >> "$GITHUB_OUTPUT"

  report:
    needs:
      - build-and-test-frontend
      - build-and-test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Summary Backend
        run: |
          echo "Lint Result Backend: ${{ needs.build-and-test-backend.outputs.lint }}"
          echo "Build Result Backend: ${{ needs.build-and-test-backend.outputs.build }}"
          echo "Test Result Backend: ${{ needs.build-and-test-backend.outputs.test }}"

      - name: Summary Frontend
        run: |
          echo "Lint Result Frontend: ${{ needs.build-and-test-frontend.outputs.lint }}"
          echo "Build Result Frontend: ${{ needs.build-and-test-frontend.outputs.build }}"
          echo "Test Result Frontend: ${{ needs.build-and-test-frontend.outputs.test }}"
